version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
